export const FETCH_CURRENT_WEATHER_START = 'FETCH_CURRENT_WEATHER_START';
export const FETCH_CURRENT_WEATHER_SUCCESS = 'FETCH_CURRENT_WEATHER_SUCCESS';
export const FETCH_CURRENT_WEATHER_FAILED = 'FETCH_CURRENT_WEATHER_FAILED';

export const FETCH_WEEKLY_WEATHER_START = 'FETCH_WEEKLY_WEATHER_START';
export const FETCH_WEEKLY_WEATHER_SUCCESS = 'FETCH_WEEKLY_WEATHER_SUCCESS';
export const FETCH_WEEKLY_WEATHER_FAILED = 'FETCH_WEEKLY_WEATHER_FAILED';